name: "Mysterium Network"
description: "Cross-platform software to run a node in Mysterium Network. It con>
version: "latest"
slug: "mysteriumNetwork"
init: true
url: "https://hub.docker.com/r/mysteriumnetwork/myst"
webui: "http://[HOST]:[PORT:4449]"
arch:
  - amd64
  - armhf
  - armv7
image: "mysteriumnetwork/myst"
port:
  4449: 4449
ingress: true
ingress_entry: dashboard/
